### ISSUE TITLE
nginx not recognising proxy_pass directives

### ISSUE THREAD

**Issue by Ilomantis** [Ansuel/tch-nginx-gui#903] opened 2020-03-07 13:58 UTC
Device Model: TG789vac v2 (VANT-6)
Gui Version: 9.5.29

Description of problem:
After updating from an earlier version (~9.5.13) nginx, and thus the gui ceases to function. 
`logread: daemon.info procd: Instance nginx::instance1 s in a crash loop 6 crashes, 0 seconds since last crash`

`nginx erorr log: unknown directive "proxy_pass" in /etc/nginx/nginx.conf:69`
nginx ver is 1.10.0, [configure arguments](https://pastebin.com/FG4bu0i5)

How to reproduce:
Update from a previous version before the new proxy_pass directives were added into the nginx config or install from scratch.

**Comment by FrancYescO** [comment] 2020-03-07 16:31
firmware?
cannot reproduce on UNO.uk 17.2

**Comment by Ilomantis** [comment] 2020-03-07 23:57
16.3.8046-ver2.5.3

**Comment by FrancYescO** [comment] 2020-03-19 11:17
fixed in https://github.com/Ansuel/tch-nginx-gui/commit/c1b921ac3c3e93970a108cd47cdd34060b921175

PS. update your router to UNO.uk 17.2

**Closed by FrancYescO** 2020-03-19 11:17 UTC
