### ISSUE TITLE
Report issue with fritz gui

### ISSUE THREAD

**Issue by Ansuel** [Ansuel/tch-nginx-gui#38] opened 2018-04-23 23:34 UTC
@SeproDE here we can report some issue and change request...

on full hd screen 15' i se 4 card instead of 5, can we fix this?

**Comment by nclmrc** [comment] 2018-04-24 06:53
If I click on language select there's a problem on the screen

**Comment by SeproDE** [comment] 2018-04-24 08:46
@Ansuel Could you provide a screenshot and browser/os you tried it on?

On my end it looks like this:
![image](https://user-images.githubusercontent.com/4618135/39176215-95abece4-47ac-11e8-8835-b51a355378b3.png)
![image](https://user-images.githubusercontent.com/4618135/39176235-9f895b16-47ac-11e8-96e5-7ba92d7a9e2e.png)
As soon as there is enough space a new column gets added.

**Comment by SeproDE** [comment] 2018-04-24 08:48
@nclmrc Could you proveda screenshot and browser/os you tried this on?

This is how it is supposed to look:
![image](https://user-images.githubusercontent.com/4618135/39176392-01271dae-47ad-11e8-9959-ee073a83dcab.png)

**Comment by emax810** [comment] 2018-04-24 08:54
@Sepro
If I use Safari (11.1.1), not show cards on homepage :



No problem with Chrome :



Thank you !


Manu 

Inviato da  Mail

**Comment by nclmrc** [comment] 2018-04-24 09:25
@SeproDE i use on Firefox.

**Comment by SeproDE** [comment] 2018-04-24 09:43
Those are the issues I was able to reproduce:

- [x] openNav is being called while in desktop view when clicking a select Element
- [ ] On Edge Sticky elements are jumpy. This is a know issue in Edge and supposed to be fixed with the Spring Creators Update
- [ ] On Edge modal footer and header are not at there right position.
- [ ] Internet Explorer doesn't limit width of sidebar
- [ ] Internet Explorer and iOS Safari title is not centered
- [ ] Mobile view not working on Internet Explorer
- [ ] No visible cards on Safari (at least on my iPad i was still able to interact with them)


I will see what I can fix. If I found a solution I will mark them off.

If you found a fix, post either the snippet here or create a pull request.

**Comment by SeproDE** [comment] 2018-04-24 12:45
@nclmrc I just created a pull request with a couple of bugfixes. Should be fixed.

**Comment by SeproDE** [comment] 2018-04-24 13:00
@emax810 This is caused by the way Safari Interpreters the overflow property and how we want a scrollbar for the sidemenu but fixed elements (that we later move) outside the sidemenu.

As far as I can tell there are two options for Safari: either we have a scrollbar for the sidemenu or we have cards.

This is the new behaviour i came up with:
 - On mobile the sidemenu is not visible at the same time as the cards. So Javascript takes care of applying the right overflow property.
 - On desktop this piece ` _::-webkit-full-page-media, _:future, :root` of css hell will (hopefully) show cards but break the scrollbar in Safari while changing nothing for other browsers.

**Comment by Ansuel** [comment] 2018-04-24 15:44
can you find a way to enable the aos animation

the loading animation doesn't show when the loading page is shown

**Comment by nclmrc** [comment] 2018-04-26 07:59
Scroll until the end of the page doesn't work in some tab in desktop mode

**Comment by SeproDE** [comment] 2018-04-26 08:41
@Ansuel I don't think it's easily possible for the card's since they already have a transform property applied to them. For the modal view I have to say that i quite like the snappy feeling of not having to wait the 0.3 seconds until the animation is finished.

**Comment by SeproDE** [comment] 2018-04-26 08:43
@nclmrc Could you provide some more information like browser and OS?

**Comment by nclmrc** [comment] 2018-04-26 08:58
@SeproDE Google chrome on android

**Comment by nclmrc** [comment] 2018-04-26 11:53
![screenshot_20180426-135005](https://user-images.githubusercontent.com/38593316/39304206-3cd1c8e2-4959-11e8-869e-7ae0eb823093.png)

**Comment by SeproDE** [comment] 2018-04-26 13:47
@nclmrc Okay, thank you for reporting this. I was able to fix it, but this breaks something on iOS. Once I figure this out I will create a pull request.

**Comment by nclmrc** [comment] 2018-04-27 05:10
@SeproDE

**Comment by nclmrc** [comment] 2018-04-28 15:50
![screenshot_20180428-174825](https://user-images.githubusercontent.com/38593316/39398345-9a33e01a-4b0c-11e8-87d5-e31f015d9d07.jpg)

**Comment by nclmrc** [comment] 2018-10-04 20:45
Qualcuno riporta ancora problemi su questo tema?

**Comment by SeproDE** [comment] 2018-10-05 09:50
I really like the new stats page. Thought it should be visible in the cards section and since the original Fritz Cards werent that usefull I decided loading the stats page via a iFrame should closere resemble the original Fritz!Box ui. Here is what i made so far: [Click](https://github.com/SeproDE/tch-nginx-gui/tree/master/decompressed/gui_file/www/docroot/theme/Fritz)

Please leave feeback before I create a PR. Should this be a seperate style or a update to the old one?

**Comment by Ansuel** [comment] 2018-10-05 10:42
Can you give me a screenshot?

Il Ven 5 Ott 2018, 11:50 Sepro <notifications@github.com> ha scritto:

**Comment by SeproDE** [comment] 2018-10-05 10:55
![image](https://user-images.githubusercontent.com/4618135/46531527-d2fcbe80-c89d-11e8-85f3-e4ea12e90292.png)

**Comment by FrancYescO** [comment] 2018-10-21 00:44
@SeproDE i like it, do a PR

**Comment by FrancYescO** [comment] 2018-10-21 07:30
in some modals (where there is a button or something with a tooltip text) under the modal cards will be shown after you hover on the button
fo example just go to the telephony modal and hover (and take the mouse out) on the bottom righ edit button

when you hover and go out from the button:
![image](https://user-images.githubusercontent.com/4574593/47264275-e782bd00-d513-11e8-886b-80823a956558.png)

when you hover again:
![image](https://user-images.githubusercontent.com/4574593/47264268-d89c0a80-d513-11e8-903e-c136dc5a28c7.png)

**Comment by SeproDE** [comment] 2018-10-21 08:39
Fixed! Created a [PR](https://github.com/Ansuel/tch-nginx-gui/pull/293).

**Comment by FrancYescO** [comment] 2018-10-21 08:57
can we put a spinner when "processing" (for example the one that appear on the end of wizard)
![image](https://user-images.githubusercontent.com/4574593/47264923-0f781d80-d520-11e8-8359-055abf073fbe.png)

**Comment by SeproDE** [comment] 2018-10-21 09:05
What Browser/OS and what Tab is the spinner not showing? This is how it looks in Chrome on Windows 10
![image](https://user-images.githubusercontent.com/4618135/47264987-400c8700-d521-11e8-97b4-cf7fb30b4719.png)

**Comment by FrancYescO** [comment] 2018-10-21 09:10
Same W10 Chrome, tryed a cache clean and just the first time the spinner is shown if i click again (on relay tab for example) the processing page is just blank, pretty strange

**Comment by FrancYescO** [comment] 2018-10-21 09:13
ps. can we remove the animation on the lateral menu? really boring that i have to wait the full page load (jquery event fired) to see it

**Comment by SeproDE** [comment] 2018-10-21 09:51
I think you are still running the old version. Try runnning the style version from my PR. Then the spinner should always be shown.

Regarding the animation. It's possible to just force the end state of the animation via the !important tag. Not pretty but it works.

**Comment by FrancYescO** [comment] 2018-10-21 19:18
Some mobile issue I noticed:
- Login page looks broken
- the bottom bar with the close button cover some content of the modal (an easy fix can be to move the close button in the upper light blue bar)

**Comment by FrancYescO** [comment] 2018-10-22 10:58
can we remove the giant word "TIM Modem" as a lot of us are not using a TIM modem? :D
![image](https://user-images.githubusercontent.com/4574593/47289215-f479dc00-d5f9-11e8-9a10-a083cbf2118a.png)

**Comment by kevdagoat** [comment] 2018-11-01 02:30
any news on this?

**Comment by SeproDE** [comment] 2018-11-01 08:49
Well the question is if we want to have the dark skins as a separately developed fork or as an add on to the Fritz theme.
If its the first this should be separately fixed if its the second someone need to port the changes I made to the Fritz skin to the other two skins.

**Comment by Ansuel** [comment] 2018-11-01 10:02
Back theme share the same script.js so only the CSS should be rebased...

Il giorno Gio 1 Nov 2018, 09:49 Sepro <notifications@github.com> ha scritto:

**Closed** 2018-11-12 14:03 UTC
Labels: skin issue
