### ISSUE TITLE
Manual Install Development Version from GitHub

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#201] opened 2018-09-20 11:32 UTC
TG800, Dev GUI Version 8.7.97

1) Downloaded [tch-nginx-gui/compressed/GUI.tar.bz2 V8.7.76](https://github.com/Ansuel/tch-nginx-gui/raw/e0b4eeca1835a027b892082358017aea369136bc/compressed/GUI.tar.bz2)
2) uploaded to /tmp
3) bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf -
4) /etc/init.d/rootdevice force

Error:
```
root@mygateway:~# /etc/init.d/rootdevice force
Root Script: Rooting in progress...
/etc/rc.common: line 1: transformer-cli: not found
ash: 1: unknown operand
```

Gui stopped until I restarted modem then came up on previous version 8.7.2. I forced upgrade through gui to dev V8.7.97. Still want Manual Install Development Version from GitHub.

**Comment by Ansuel** [comment] 2018-09-20 13:28
do rootdevice debug pls

**Comment by kevdagoat** [comment] 2018-09-20 23:19
I get the same problem with all of my Telstra modems.

**Comment by FrancYescO** [comment] 2018-09-21 08:07
The issue is simple: the dev full packages is NOT uploaded to github in the compressed dir, you have no way to get an older dev version, but only the latest from ilpuntotecnico repo

**Comment by flywire** [comment] 2018-09-21 09:04
https://github.com/Ansuel/tch-nginx-gui/issues/107#issuecomment-423126883
> Something changed in the newest dev

Given my code was working fine previously it makes it hard for me to understand changes that were made in devs.

**Comment by Ansuel** [comment] 2018-09-21 13:20
GUI.tar.bz2 is stable

dev build are on ilpuntotecnico repo 

dev version are downloaded from there not from github...

**Comment by Ansuel** [comment] 2018-09-21 13:29
last

**Comment by flywire** [comment] 2018-09-21 13:36
Last Dev always at: https://repository.ilpuntotecnico.com/files/Ansuel/AGTEF/GUI_dev.tar.bz2

**Comment by flywire** [comment] 2018-09-22 08:13
@Ansuel
Would you consider archiving the devs?
Alternatively, could we create them from github? Maybe using you current (or modified) process to generate them.

**Comment by FrancYescO** [comment] 2018-09-22 08:15
checkout with git the commit of your interest and run `create_zip_dev.bat`

**Comment by flywire** [comment] 2018-09-22 09:48
Using GitHub Desktop (Win10).

What does checkout mean? Using https://github.com/Ansuel/tch-nginx-gui/commit/e0b4eeca1835a027b892082358017aea369136bc as example I assume you mean click on it to download.

> create_zip_dev.bat

Not found on my computer.

**Comment by flywire** [comment] 2018-09-24 11:17
Is GitHub one commit behind  https://repository.ilpuntotecnico.com/files/Ansuel/AGTEF ?

**Comment by FrancYescO** [comment] 2018-09-24 11:32
Sometime yes.
________________________________

**Comment by flywire** [comment] 2018-09-28 09:09
https://github.com/Ansuel/tch-nginx-gui/issues/223#issuecomment-425251829

**Comment by kevdagoat** [comment] 2018-11-24 23:38
This should be fixed

**Comment by Janaue** [comment] 2018-11-25 04:10
should '/etc/init.d/rootdevice force' be used even for upgrading from a dev GUi to another dev GUI ?
When i try to update a dev GUI to a dev GUi, I do


>     Downloaded https://repository.ilpuntotecnico.com/files/Ansuel/AGTEF/GUI_dev.tar.bz2 
>     uploaded to /tmp
>     bzcat /tmp/GUI_dev.tar.bz2 | tar -C / -xvf -
>     /etc/init.d/transformer restart
>     /etc/init.d/nginx restart

but the GUI version stays the same on http://10.0.0.138/gateway.lp#
I always have to update through the GUI afterwards, to get the updated version to show on http://10.0.0.138/gateway.lp#

**Comment by Janaue** [comment] 2018-11-25 07:20
IS there a reboot of the device after '/etc/init.d/rootdevice force' is executed ?

**Comment by FrancYescO** [comment] 2018-11-25 08:50
Why don't just use the built-in method for upgrade? (Upgrade button in gateway modal)
________________________________

**Comment by Janaue** [comment] 2018-11-25 10:51
the built-in method  sometimes hangs, both with getting the GUI online and the one where I point to the GUI on the HDD

**Comment by FrancYescO** [comment] 2018-11-25 11:40
explain "hangs".
use `upgradegui` to give useful debug infos

**Comment by Janaue** [comment] 2018-11-26 07:38
hangs = either there is no updating bar showing, so it stays like that forever
![sshot-179](https://user-images.githubusercontent.com/10972636/48999093-e1f14600-f155-11e8-881c-ca8b4ac2369b.jpg)

or if there is the update bar, the bar does not progress and stays at the beginning


but when I manully put the dev GUi in \tmp folder and do 

bzcat /tmp/GUI_dev.tar.bz2 | tar -C / -xvf -

then click on ''force upgrade'' in the gui, the update bar shows and progresses and it updates well.

the command gives 


root@mygateway:~# upgradegui

Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: 5d3229615f567801468357e2b3516a0e
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
Upgrade Script: Stable version found: 8.08.77
Upgrade Script: Dev version found: 8.09.74
Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
Upgrade Script: Upgrade Done
root@mygateway:~#


then after this update, I go to http://10.0.0.138/gateway.lp# but nothing loads up. I need to do 

/etc/init.d/transformer restart
/etc/init.d/nginx restart

to get the login page

**Comment by kevdagoat** [comment] 2018-11-27 00:41
Of course the bar won’t work!
When the upgrade script first runs it stops nginx, the daemon that runs the web interface and updates the progress bar.

**Comment by FrancYescO** [comment] 2018-11-27 02:05
something got broken in the latest dev release as it was warking flawlessy before

**Comment by FrancYescO** [comment] 2018-12-05 15:52
this is basically implemented.
you will find all builds in this repo https://github.com/Ansuel/gui-dev-build-auto

**Closed by FrancYescO** 2018-12-05 15:52 UTC
Labels: enhancement
