### ISSUE TITLE
Network restart on upgrade and ipv6 problem

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#78] opened 2018-07-15 14:50 UTC
After the update to the last versions,  i always must restart Internet access from tab to come newly online.

**Comment by onix20** [comment] 2018-07-15 15:00
Me too (Router modus). I get this  in Log-Viewer:

2018/07/15 09:33:00 [error] 8708#0: *177 lua entry thread aborted: runtime error:
[string "internet-pppoe-routed.lp"]:317: attempt to index global 'c' (a nil value)

**Comment by nclmrc** [comment] 2018-07-15 15:01
The log:
# Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Apply specific DGA file...
Root Script: Extracting custom-ripdrv-specificDGA.tar.bz2 ...
Root Script: telnet_support-specificDGA.tar.bz2 ...
Root Script: Extracting upgrade-pack-specificDGA.tar.bz2 ...



Root Script: Extracting upnpfix-specificDGA.tar.bz2 ...
Root Script: Extracting dlnad_supprto-specificDGA.tar.bz2 ...
Root Script: Removing specific file and resuming root process...
Root Script: Disable watchdog
Root Script: Start rooting
Root Script: Stopping nginx and transformer
Root Script: Checking if we are on TIM configuration
Root Script: Unlocking web interface if needed
Root Script: Check and cleanup
Root Script: Remove default dns
Root Script: Purify wan
Root Script: Fix dns bug
Root Script: Enable dlnad
ILibStartChain: Exit main loop
Root Script: Fix Sysupgrade
Root Script: Check orig config
Root Script: Trafficmon inizialization
Intel MicroStack 1.0 - Digital Media Server (DLNA 1.5)(pid = 26800),

Root Script: Restore original mapper
Root Script: Transformer lib check
Root Script: Remove https check
Root Script: Check css presence
Root Script: Check if dnsmasq is names as we need it for the webui
Root Script: Check driver setting
Root Script: Check Dropbear config file
Root Script: Check ddns directory
Root Script: Check eco param
Root Script: Enable new upnp
Root Script: Sync dhcp configuration for new webui
Root Script: Create gui type in config
Root Script: Add new web option
Root Script: New DHCPRelay Option
Root Script: Disable trace from igmpproxy
Root Script: Moving aria2 dir
Root Script: Creating new option for led definition
Root Script: Old build detected, moving wansensing file
Root Script: Checking downgrade limitation bit
Root Script: Checking opkg conf
Root Script: Creating and checking real version
Root Script: Creating new wol implementation
Root Script: Sync new xdsl option
Root Script: Creating utility simbolic link
Root Script: Clean old script
Root Script: Adding fast cache options
Flow Cache Setting: Starting service...
Flow Cache Setting: Setting l2tp options to 1
Flow Cache Setting: Setting gre options to 1
Flow Cache Setting: Setting ipv6 options to 1
Flow Cache Setting: Setting mcast options to 1
Flow Cache Setting: Setting mcast-learn options to 1
Root Script: Reworking sfp interface in network...
Root Script: Moving sfp to sfptag...
uci: Entry not found
Success
JUMBO_PORT_MASK:0x00000000
  GPHY_0 port rejects jumbo frames.
  GPHY_1 port rejects jumbo frames.
  GMII_1 port rejects jumbo frames.
  GMII_2 port rejects jumbo frames.
  GPON_SERDES port rejects jumbo frames.
  MOCA port rejects jumbo frames.
  USB port rejects jumbo frames.
  GPON port rejects jumbo frames.
  MIPS port rejects jumbo frames.
Success
Root Script: Setting root flag
Root Script: Disable reboot after crash, this gives race condition...
Root Script: Save root password if modified
Root Script: Setting dropbear settings
Root Script: Doing various check and generating hash...
Root Script: Sync version
Root Script: Apply modification
Root Script: Restart power init
Root Script: Restarting dropbear
interface lan has no physdev or physdev has no suitable ip
interface wan has no physdev or physdev has no suitable ip
Root Script: Restarting dnsmasq
Root Script: Process done.
Root Script: Checking if ISP is detected...
Root Script: Restarting transformer
Root Script: Waiting transformer to start for 20 seconds
Root Script: Restarting nginx
Root Script: Restarting transformer a second time cause it's just shit...
Root Script: Resetting cwmp and watchdog
Upgrade Script: Upgrade Done

**Comment by Ansuel** [comment] 2018-07-15 15:01
modem ? agthp ?

**Comment by nclmrc** [comment] 2018-07-15 15:04
Yes dga4132

**Comment by Ansuel** [comment] 2018-07-15 15:05
give me /etc/config/network

**Comment by nclmrc** [comment] 2018-07-15 15:09
config interface 'loopback' 	option ifname 'lo' 	option proto 'static' 	option ipaddr '127.0.0.1' 	option netmask '255.0.0.0' config globals 'globals' 	option ula_prefix 'none' 	option default_ps '0' config device 'waneth4' 	option type '8021q' 	option name 'waneth4' 	option macaddr 'A4:91:B1:2B:08:EC' 	option ifname 'eth4' 	option vid '835' 	option ipv6 '0' config device 'wanptm0' 	option type '8021q' 	option name 'wanptm0' 	option macaddr 'A4:91:B1:2B:08:EC' 	option ifname 'ptm0' 	option vid '835' 	option ipv6 '0' config interface 'wan' 	option proto 'pppoe' 	option demand '0' 	option macaddr 'A4:91:B1:2B:08:EC' 	option ipv6 '0' 	option keepalive_adaptive '0' 	option dns_metric '0' 	option ifname 'atmwan' 	option username 'R23012' 	option metric '0' 	option password 'marchi' 	option auto '1' config interface 'wanvoip' 	option auto '1' 	option proto 'pppoe' 	option demand '0' 	option macaddr 'A4:91:B1:2B:08:EB' 	option ipv6 '0' 	option peerdns '1' 	option reqopts '1 3 6 15 33 42 51 121 249' 	option keepalive_adaptive '0' 	option dns_metric '0' 	option password 'marchi' 	option username 'vR23012' 	option ifname 'atmwanvoip' config config 'config' 	option wan_mode 'pppoe' config interface 'wwan' 	option proto 'mobiled' 	option session_id '0' 	option profile '1' 	option auto '0' config interface 'wan6' 	option proto 'dhcpv6' 	option reqopts '12 21 22 23 24 25 31 56 64 67 82 83' 	option noslaaconly '1' 	option iface_464xlat '0' 	option auto '0' 	option dns_metric '20' 	option ifname '@wan_ipv6' config interface 'sfptag' 	option proto 'static' 	option ifname 'eth4' 	option netmask '255.255.255.0' 	option ipaddr '192.168.10.1' config interface 'lan' 	option type 'bridge' 	option proto 'static' 	option netmask '255.255.255.0' 	option ip6assign '64' 	option force_link '0' 	option ipv6 '0' 	option ifname 'eth0 eth1 eth2 eth3 eth5' 	list pppoerelay 'atmwan' 	option ipaddr '192.168.1.254' config switch 'bcmsw' 	option reset '1' 	option enable_vlan '0' 	option qosimppauseenable '0' 	option jumbo '0' config interface 'wlnet_b_24' 	option proto 'static' 	option ip6assign '64' 	option ipv6 '0' 	option ip6hint '1' 	option netmask '255.255.255.128' 	option ipaddr '192.168.168.1' 	option ifname 'wl0_1' 	option force_link '0' 	option name 'Ospiti-TIM-19597549' config interface 'wlnet_b_5' 	option proto 'static' 	option ip6assign '64' 	option ipv6 '0' 	option ip6hint '2' 	option netmask '255.255.255.128' 	option ipaddr '192.168.168.129' 	option ifname 'wl1_1' 	option force_link '0' 	option name 'Ospiti-TIM-19597549' config device 'wlnet_b_5eth5' 	option type '8021q' 	option name 'wl1_1' 	option enabled '1' 	option ifname 'eth5' 	option vid '3' 	option ipv6 '0' config interface 'ipoe' 	option proto 'dhcp' 	option metric '1' 	option reqopts '1 3 6 43 51 58 59' 	option release '1' 	option neighreachabletime '1200000' 	option neighgcstaletime '2400' 	option ipv6 '1' config route 	option interface 'wanvoip' 	option gateway '10.56.17.1' 	option netmask '255.255.192.0' 	option metric '1' 	option target '10.56.0.0' config route 	option interface 'wanvoip' 	option gateway '10.56.17.1' 	option netmask '255.255.255.0' 	option metric '1' 	option target '5.43.239.0' config route 	option interface 'lan' 	option gateway '192.168.1.1' 	option netmask '255.255.255.0' 	option metric '1' 	option target '10.8.0.0'

**Comment by nclmrc** [comment] 2018-07-15 15:10
https://pastebin.com/WmjQBmgz

**Comment by Ansuel** [comment] 2018-07-15 15:12
/etc/init.d/rootdevice force still restart internet?

**Comment by nclmrc** [comment] 2018-07-15 15:15
No perché upgradegui esegue quel comando. Ma Internet non riparte da solo. Ti torna?

**Comment by nclmrc** [comment] 2018-07-15 15:29
Si è resettato nuovamente

**Comment by Ansuel** [comment] 2018-07-15 15:33
dovrei aver fixato

**Comment by nclmrc** [comment] 2018-07-15 15:37
Grande. Una domanda ulteriore come mai sei nella nella configurazione del VoIP imposto un interfaccia dedicata, sono costretto a mettere le rotte statiche e non una default Route per quell'interfaccia con metrica 1?

**Comment by Ansuel** [comment] 2018-07-15 15:38
probabilmente è causato da script vecchi di openwrt

**Comment by nclmrc** [comment] 2018-07-15 15:40
Come potrei fare a capirlo?

**Comment by onix20** [comment] 2018-07-15 16:00
My problem with the dga4132 is still there (Gui 8.6.2).

2018/07/15 17:49:46 [error] 7535#0: *29 lua entry thread aborted: runtime error: [string "internet-pppoe-routed.lp"]:317: attempt to index global 'c' (a nil value)

**Comment by Ansuel** [comment] 2018-07-15 16:07
@onix20 you have ipv6 enabled right?

anyway with thise new version should be fixed

**Comment by onix20** [comment] 2018-07-15 16:07
Yes

**Comment by Ansuel** [comment] 2018-07-15 17:05
@onix20 can you confirmi that the problem is solved ?

**Comment by onix20** [comment] 2018-07-15 20:16
Wenn I enabled ipv6, I cannot connect to Internet.

**Closed** 2018-09-29 20:33 UTC
Labels: bug, fixed, waiting for feedback
