### ISSUE TITLE
Traffic Monitor in Telstra GUI not working

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#244] opened 2018-10-01 23:19 UTC
Device Model: DGA4132 1.2.0 / TG789 UNO 17.2
Gui Version: 8.8.37

Description of problem: Traffic Monitor in Telstra GUI (Services>Traffic Monitor) is not working it just show a blank page

```
Tue Oct  2 01:18:46 2018 daemon.err nginx: 2018/10/02 01:18:46 [error] 796#0: *31 attempt to set status 500 via ngx.exit after sending out the response status 200, client: 192.168.1.77, server: localhost, request: "GET /telstra-modals/traffic.lp?iface=wl0 HTTP/1.1", host: "192.168.1.1", referrer: "http://192.168.1.1/telstra-modals/dyndns.lp"
Tue Oct  2 01:18:46 2018 daemon.err nginx: 2018/10/02 01:18:46 [error] 796#0: *31 open() "/www/docroot/js/graphic-min.js" failed (2: No such file or directory), client: 192.168.1.77, server: localhost, request: "GET /js/graphic-min.js HTTP/1.1", host: "192.168.1.1", referrer: "http://192.168.1.1/telstra-modals/traffic.lp?iface=wl0"
Tue Oct  2 01:18:46 2018 daemon.err nginx: 2018/10/02 01:18:46 [error] 796#0: *31 open() "/www/docroot/js/graphic-min.js" failed (2: No such file or directory), client: 192.168.1.77, server: localhost, request: "GET /js/graphic-min.js HTTP/1.1", host: "192.168.1.1", referrer: "http://192.168.1.1/telstra-modals/traffic.lp?iface=wl0"

```

**Comment by kevdagoat** [comment] 2018-10-01 23:27
Looks like the script that it is referring to doesn’t exist.

**Comment by FrancYescO** [comment] 2018-10-02 10:29
the missing `graphic-min.js` file is not the only issue, also after a restore the error 500 still here and the page shows half-empty so i would ask if on telstra firmwares this was working good

**Comment by flywire** [comment] 2018-10-02 20:10
Duplicate to https://github.com/Ansuel/tch-nginx-gui/issues/107#issuecomment-418237460. Works in original Telstra gui.

**Comment by FrancYescO** [comment] 2018-10-03 00:35
@flywire or @kevdagoat could you post here `/root/trafficmon/` folder? seems is something related to the content of this dir...

**Comment by flywire** [comment] 2018-10-03 02:41
@FrancYescO - Check PM I sent you on the Italian Forum a few weeks ago (unencrypted files).

**Comment by FrancYescO** [comment] 2018-10-03 09:02
@flywire i have only the www dir this folder is under /root/

**Comment by flywire** [comment] 2018-10-03 09:46
Traffic Monitor does not work on my system because it is screwed. I don't want to reflash it until I sort out https://github.com/Ansuel/tch-nginx-gui/issues/197 to reload vnstat after each reflash. I'll find another modem and check /root.

**Comment by FrancYescO** [comment] 2018-10-03 09:55
if you have a script that enable vnstats for our gateway share it

**Comment by flywire** [comment] 2018-10-03 10:34
https://drive.google.com/file/d/1BplnYw2rSlw6YF29EOr_UBRvOqAioSmn/view?usp=sharing

**Comment by flywire** [comment] 2018-10-03 12:07
Ansuel eliminated a few [duplicate] files when porting across and Traffic Monitor is really a duplicate of tch-nginx-gui modal.

Happy to give more support if there are features you want to extract.

**Comment by FrancYescO** [comment] 2018-10-03 12:10
i just want that the GUI is fully working no matther that is a duplicate (all the Telstra GUI in my point of view is a useless duplicate :D )

**Closed** 2018-10-30 15:47 UTC
Labels: bug, fixed
