### ISSUE TITLE
Setting to disable all effects

### ISSUE THREAD

**Issue by xes** [Ansuel/tch-nginx-gui#546] opened 2019-03-04 13:00 UTC
Even if most part of user, use super fast browsers on super updated hardware... 
Someone still has obsolete browsers on pretty slow hardware.  And, since it's just a router... 

Please give the possibility to globally disable all the effects, animations and cards popups to allow to manage the router also using old hardware/browsers. Thanks!

**Comment by Ansuel** [comment] 2019-03-04 18:14
i add an option to disable most of them

**Comment by xes** [comment] 2019-03-05 16:58
thank you very much. 
..But still cards loading animation in every rectangle seems to slow down a lot. 
It's just me?

**Comment by Ansuel** [comment] 2019-03-06 15:22
We are doing some test about it... We also notice some delay in the loading and we are searching the cause. In the next stable will not be there anyway so...

**Comment by FrancYescO** [comment] 2019-03-17 15:35
Closing as this got implemented

**Closed by FrancYescO** 2019-03-17 15:35 UTC
Labels: enhancement
