### ISSUE TITLE
"invalid instance" when opening Wizard

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#118] opened 2018-08-27 12:53 UTC
Tiscali 16.3 - GUI 8.7.2
Just open wizard and i'll get "Invalid instance"
https://i.imgur.com/rsOtVbT.png

**Comment by Ansuel** [comment] 2018-08-27 18:13
i need the network file... in config

**Comment by FrancYescO** [comment] 2018-08-27 19:02
taken from a backup from another Tiscali modem but is pretty the same with just the censored values changed:
[network.zip](https://github.com/Ansuel/tch-nginx-gui/files/2325243/network.zip)

ps. pay attention that i was using "assist" user (with remote assistance) that seems have no permission also for change via GUI the PPPoE credentials

**Comment by Ansuel** [comment] 2018-08-27 20:13
O think it's just some problem with the different configuration of the
modem

Il Lun 27 Ago 2018, 21:02 Francesco M <notifications@github.com> ha scritto:

**Comment by flywire** [comment] 2018-09-01 07:46
Same issue in initial image. TG800vac version 8.7.24.

**Comment by FrancYescO** [comment] 2018-09-01 08:11
Replacing 
https://github.com/Ansuel/tch-nginx-gui/blob/f75c53cd6727307687c967fe05311dfcb84abb81/decompressed/gui_file/www/wizard-cards/001_broadband.lp#L39
with:
```
local wan_atm_uci_path = "uci.xtm.atmdevice.@atm_8_35."
local wan_atm_uci_ipoe_path = "uci.xtm.atmdevice.@atm_8_35."
```
But this is probably a Tiscali firmware requirement. Seems we should find a way to autodetect the atm interface name to be compatible on all devices/software variants

This solved at least the first page wizard issue, https://github.com/Ansuel/tch-nginx-gui/issues/97 this still happen.

**Comment by Ansuel** [comment] 2018-09-01 09:02
I personally tested #97 and k can insert empty value...

Il Sab 1 Set 2018, 10:11 Francesco M <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment] 2018-09-01 09:04
The real problem is the custom implementation of the Tiscali firmware

Il Sab 1 Set 2018, 11:02 Ansuel Smith <ansuelsmth@gmail.com> ha scritto:

**Comment by Ansuel** [comment] 2018-09-01 19:31
It's not so easy I can put a check for the different configuration but it would not work so well as any difference would cause problems...

**Comment by flywire** [comment] 2018-09-02 12:59
Curious that problem disappears after going to page 2 then back to page 1. 

Maybe this will help from my config file:

[xtm]
xtm.ptm0=ptmdevice
xtm.ptm0.priority='low'
xtm.atm_8_35=atmdevice
xtm.atm_8_35.enc='llc'
xtm.atm_8_35.vpi='8'
xtm.atm_8_35.ulp='eth'
xtm.atm_8_35.path='fast'
xtm.atm_8_35.vci='35'

**Comment by FrancYescO** [comment] 2018-09-02 13:07
So seems at least Telstra is using the same interface name..

As a fast solution the check with a list of known interface names seems usable

**Comment by Ansuel** [comment] 2018-09-04 20:07
can someone try this new version ?

**Comment by flywire** [comment] 2018-09-04 20:29
Same error page 1 and 2.

**Comment by Ansuel** [comment] 2018-09-05 14:41
can you give me the network of the uno firmware

**Comment by FrancYescO** [comment] 2018-09-05 14:50
[network.zip](https://github.com/Ansuel/tch-nginx-gui/files/2353256/network.zip)

**Comment by Ansuel** [comment] 2018-09-05 15:01
sorry the xtm config file...

**Comment by FrancYescO** [comment] 2018-09-05 15:02
```

config ptmdevice 'ptm0'
	option priority 'low'

config atmdevice 'atm0'
	option ulp 'ppp'
	option vpi '0'
	option vci '38'
	option path 'fast'
	option enc 'vcmux'

```

**Comment by Ansuel** [comment] 2018-09-05 15:09
then i think the problem is in another value...

**Comment by FrancYescO** [comment] 2018-09-05 17:34
probably we need a dummy connection for eth or some dummy datas on interfaces... il try to get exactly what is missing do you have some tips to speedup my search?

**Comment by FrancYescO** [comment] 2018-09-05 23:33
The issue seems to be `uci.network.device.@waneth4.vid`...

**Comment by FrancYescO** [comment] 2018-09-06 00:33
And there are 2 values `ppp_username` and `ppp_password` that are duplicate of `wan_ppp_user_name` and  `wan_ppp_password` and should be removed, than i think we need, on rootscript, a check to add a placeholder for a `waneth4` if missing (on UNO firmware) and we are ready to go

@flywire how is your wan ETH device named? could you post your /etc/config/network and xtm files?

**Comment by flywire** [comment] 2018-09-06 00:56
/etc/config/network

```
config interface 'loopback'
	option ipaddr '127.0.0.1'
	option proto 'static'
	option netmask '255.0.0.0'
	option ifname 'lo'

config globals 'globals'
	option ula_prefix 'fd0d:b168:15e7::/48'
	option default_ps '0'

config interface 'lan'
	option ipaddr '10.0.0.138'
	option netmask '255.255.255.0'
	list pppoerelay ''
	option proto 'static'
	option ip6hint '0'
	option ip6assign '64'
	option type 'bridge'
	option force_link '0'
	option ifname 'eth0 eth1 eth2 eth3'

config interface 'Guest1'
	option ipaddr '192.168.2.126'
	option ip6hint '1'
	option netmask '255.255.255.128'
	option ifname 'wl0_1'
	option ip6assign '64'
	option force_link '0'
	option proto 'static'

config interface 'Guest1_5GHz'
	option ipaddr '192.168.2.254'
	option ip6hint '2'
	option netmask '255.255.255.128'
	option ifname 'wl1_1'
	option ip6assign '64'
	option force_link '0'
	option proto 'static'

config switch 'bcmsw'
	option qosimppauseenable '0'
	option enable_vlan '0'
	option reset '1'

config interface 'ppp'
	option keepalive '4,20'
	option iface6rd '0'
	option username 'home@example.com'
	option metric '10'
	option graceful_restart '1'
	option proto 'pppoe'
	option auto '0'
	option ifname 'atm_8_35'

config interface 'ipoe'
	option reqopts '1 3 6 43 51 58 59'
	option ipv6 '1'
	option neighgcstaletime '2400'
	option iface6rd '0'
	option neighreachabletime '1200000'
	option vendorid 'technicolor'
	option metric '1'
	option release '1'
	option proto 'dhcp'
	option auto '0'

config interface 'wan6'
	option reqaddress 'none'
	option reqopts '23 25'
	option iface_464xlat '0'
	option noslaaconly '1'
	option proto 'dhcpv6'
	option ifname 'eth4'

config interface 'wwan'
	option profile '1'
	option proto 'mobiled'
	option session_id '0'
	option enabled '0'

config device 'eth4'
	option mtu6 '1500'
	option neighgcstaletime '2400'
	option neighreachabletime '1200000'
	option name 'eth4'
	option mtu '1500'

config device 'atm_8_35'
	option name 'atm_8_35'
	option neighreachabletime '1200000'
	option neighgcstaletime '2400'

config device 'ptm0'
	option name 'ptm0'
	option neighreachabletime '1200000'
	option neighgcstaletime '2400'

config ppp_placeholder
	option uciname 'pppoe-wan'

config interface 'fonopen'
	option ipaddr '192.168.20.1'
	option netmask '255.255.255.0'
	option ip6class 'wan6'
	option proto 'static'
	option ipv6 '1'
	option auto '0'
	option force_link '0'
	option type 'bridge'

config config 'config'

config interface 'wan'
	option reqopts '1 3 6 43 51 58 59'
	option proto 'dhcp'
	option release '1'
	option iface6rd '0'
	option neighreachabletime '1200000'
	option vendorid 'technicolor'
	option metric '1'
	option neighgcstaletime '2400'
	option ipv6 '1'
	option ifname 'eth4'
```

/etc/config/xtm

```
config ptmdevice 'ptm0'
	option priority 'low'

config atmdevice 'atm_8_35'
	option vci '35'
	option vpi '8'
	option ulp 'eth'
	option enc 'llc'
	option path 'fast'
```

**Comment by flywire** [comment] 2018-09-06 01:50
Not right for ethernet:

![Setup Wizard page 8 of 8](https://image.ibb.co/kj2Fnz/https://image.ibb.co/kj2Fnz/Setup_Wizard8of8.png.png)

**Comment by flywire** [comment] 2018-09-18 20:45
Gui Version: 8.7.91 on ethernet:

![Setup Wizard page 1 of 8](https://image.ibb.co/dEAWPz/Setup_Wizard1of8.png)

![Setup Wizard page 8 of 8](https://image.ibb.co/eX6SxK/Setup_Wizard8of8b.png)

**Comment by FrancYescO** [comment] 2018-09-18 23:30
@flywire under broadband card options do you have the block to switch mode?
![image](https://user-images.githubusercontent.com/4574593/45722123-38b52f00-bbab-11e8-82f2-faf3bf67310d.png)

try to set VDSL2 and than back to your connection type (ETH?) this fixed the issue of wizard for me on UNO firmware

**Comment by flywire** [comment] 2018-09-19 21:35
@FrancYescO - makes no difference. btw - When I switch to VDSL2 and close it opens back up in ETH.

If you got my PM on ilpuntotecnico please reply.

**Comment by FrancYescO** [comment] 2018-09-19 22:52
@flywire you probably have also to set a VLAN id on the bottom, than wizard should work good

**Comment by FrancYescO** [comment] 2018-09-19 23:28
you still have something wrong when u set ethernet?

**Comment by flywire** [comment] 2018-09-19 23:59
No problem after workaround but workaround is unreasonable, especially for target user which is noob.

**Comment by FrancYescO** [comment] 2018-09-20 00:07
yes infact we are going to find a way to solve, was just to confirm that is working good in this manner also on Telstra

**Closed** 2018-09-22 17:39 UTC
Labels: bug
