### ISSUE TITLE
Help Wanted: Luci Support

### ISSUE THREAD

**Issue by Ansuel** [Ansuel/tch-nginx-gui#159] opened 2018-09-05 15:40 UTC
Someone should really help me with Luci

At this time... Luci works but some part are broken... For example someone should add support for xdsl stats and also someone should fix the wireless page... 

I can but for now it's not my priority as to use luci we need to first compile specific package (uhttpd and rcpd mainly) 

Luci can be installed on DGA4130 and DGA4132

**Comment by kevdagoat** [comment] 2018-09-05 23:06
There is already a user compiling this. He reported it working. You will have to wait until I can grab the source off him

**Comment by kevdagoat** [comment] 2018-09-06 00:37
(For tg789, 799, 800)

**Comment by kevdagoat** [comment] 2018-09-06 00:47
Will help.
Here is a page about developing luci for the tg789v2 
https://alastair.d-silva.org/technicolor-tg789vac-v2-root-access

**Comment by nutterpc** [comment] 2018-09-07 04:02
That person would be me Ansuel, that kevdagoat is referring to

The code has been Verified with the following devices myself:

TG789VAC-V2
TG799VAC-V2

Haven't tested the TG797n-V3 yet. And the TG800 due to different arch, will need a little more time

And kev, that guide isn't overly helpful in that it's steps are a little lacking. I was looking at it to start off with, but found that there's a lot the guy DIDN'T list

Email me ansuel. I'll let you know where I'm up to. I've got a roadmap in place for moving forward

just add @nutterpc.com
kevdagoat knows. Don't repeat it on here though. Easy enough to work out 📦

**Comment by kevdagoat** [comment] 2018-09-07 04:27
If you want I will verify it on a tg797n v3

**Comment by Ansuel** [comment] 2018-09-07 10:34
if tg800 and tg799 are based on arm the dga package should install and work just right...

**Comment by Ansuel** [comment] 2018-09-07 10:37
@nutterpc why not talk here?

**Comment by kevdagoat** [comment] 2018-09-07 11:03
Tg799 is mips

**Comment by kevdagoat** [comment] 2018-09-07 11:04
We want to keep it away from prying technicolor eyes

**Comment by FrancYescO** [comment] 2018-09-07 11:06
@kevdagoat for what? if they read us at least they will add LuCI to their firmware :D

**Comment by kevdagoat** [comment] 2018-09-07 23:33
I don’t think that will happen!!

**Comment by FrancYescO** [comment] 2018-09-08 01:05
That's why you can feel free to talk here :P
________________________________

**Comment by kevdagoat** [comment] 2018-09-08 04:29
I asked nutterpc and he didn’t want to. I thought that was fair enough, as he has spent most of his week on it.

**Comment by nutterpc** [comment] 2018-09-08 23:53
As i explained on our thread on Whirlpool Forums, my nature is that I want to test it privately myself to ensure that everything works as expected.

Plus, I want to get the TG800 Build done and dusted as well. So that way it can be had on all of them effectively, if its possible due to firmware limitations

**Comment by FrancYescO** [comment] 2018-09-09 00:03
take us updated :) ... with no public infos you cannot have community support :P

**Comment by nutterpc** [comment] 2018-09-09 01:28
That's the proof Ansuel that she's working thus far, very well even

**Comment by Ansuel** [comment] 2018-09-09 01:58
Actually Luci works well
Problem is with wireless and DSL stats that needs to be rewritten to adapt
to the xdslctl bin



Il Dom 9 Set 2018, 03:28 Nutterpc <notifications@github.com> ha scritto:

**Comment by nutterpc** [comment] 2018-09-09 02:02
The wireless bit is something interesting, I did initially get it reporting properly, but then id segfaulted the router, forgot to backup the config haha

So now I'm trying to get a build environment for OpenWRT that works so I can make the builds a lot faster

**Comment by nutterpc** [comment] 2018-09-09 02:08
Soon as I can get a stable build environment that doesn't complain every 5 mins about SOMETHING, then I'll happy. because right now, it's annoying it keeps failing for random/weird/no reason on packages

Then you have to go into the code and either build into the kernel or remove it to get it to continue building

Hopefully in a few weeks I'll have a new PC (For me at least)

Going from this Toshiba Core i7 laptop to hopefully a Dell Xeon Workstation, either 4 or 6 core w/HT & 24Gb RAM :)

**Comment by nutterpc** [comment] 2018-09-09 07:57
For $500-600 i cant argue, lol

**Comment by kevdagoat** [comment] 2018-09-09 09:07
Pretty good price

Sent from Mail for Windows 10

**Comment by nutterpc** [comment] 2018-09-10 03:15
Well Ansuel & Francyesco

If the packages I'm compiling now successfully complete testing, these will form the basis of the stable build environment. I'll then move onto building some for the last one in the list: TG800

As I know a good friend of mine has one, I'll get him to test them for me. Then once all the testing has been completed & I'm happy it's worked as expected, I'll upload it to my github

I've got a spare TG799VAC sitting on my desk beside me for the very reason, to test this latest batch compiling

**Comment by kevdagoat** [comment] 2018-09-10 04:12
I look forward to help implement mmpbxd and xdsl.
Will work great on github.

**Comment by nutterpc** [comment] 2018-09-11 05:02
I've been battling my way through some bugs trying to get the stuff to compile (had a fairly sleepless night the last few nights), but seem to have been making progress.

Will be testing this latest batch that's almost finished compiling as soon as she finishes
Then its test build the TG800 Packages, get them verified, then once thats done, I'll finally be happy

**Comment by nutterpc** [comment] 2018-09-11 13:45
The TG800 build is commencing now Ansuel. Wish me luck lol. This is going to be the biggest challenge of all, getting luci to run on a device with no known full repos hahaha

**Comment by nutterpc** [comment] 2018-09-14 01:38
Well I've made strides in getting LUCI running on the TG800

We got all but *ONE* program to install correctly. it segfaulted with an error of illegal instruction

So not bad to go from Alpha 1 Packages only 1 installed, to Alpha 2 Packages that all but ONE installed

And which one is it you want to know that segfaulted on me?

rpcd lol

**Comment by kevdagoat** [comment] 2018-09-14 04:38
Always rpcd 😊

Sent from Mail for Windows 10

**Comment by nutterpc** [comment] 2018-09-18 10:08
As soon as my friend gets home, we will be testing Alpha 3 Packages again, except cutting out a few to see if it sticks

The positive bit is, we *may* have a dual purpose ipk. Will wait and see how testing goes, then will be able to release them hopefully this weekend

**Comment by nutterpc** [comment] 2018-09-18 10:54
Hey these ones may very work for both, plus the past few days i been working so had no time to do anyting

**Comment by nutterpc** [comment] 2018-09-18 22:30
As per my WP post, the packages used to get luci running will be released this weekend (22-23 Sep)

I will be finalising everything needed during the rest of this week, to allow for me to finally release it into the wild this weekend :)

**Comment by kevdagoat** [comment] 2018-09-19 09:43
Btw @Ansuel 
love your modifications to the xdsl card!

**Comment by nutterpc** [comment] 2018-09-22 23:28
Files have been released. Look to my Whirlpool post. As Agreed I'd do it this weekend :)

**Comment by FrancYescO** [comment] 2018-09-23 00:09
Link it :)

**Comment by nutterpc** [comment] 2018-09-23 00:10
http://whrl.pl/RfexnQ

**Comment by kevdagoat** [comment] 2018-09-23 09:08
That’s good!

**Comment by nutterpc** [comment] 2018-09-23 10:59
Franc has confirmed 17.2 install on a TG789v2 UNO

**Comment by FrancYescO** [comment] 2018-09-28 00:45
Basically the install script is ready I don't know if @Ansuel want to integrate with a compressed file or is okay to download on the fly from nutterpc github what is really needed is a revert script to clean all the Installed ipks edited files
________________________________

**Comment by kevdagoat** [comment] 2018-09-28 00:59
Download on the fly is the go, otherwise we will clutter the modems storage massively.

**Comment by kevdagoat** [comment] 2018-09-28 01:00
> revert script to clean all the Installed ipks 

Shouldn’t be too hard. opkg remove should work.

**Comment by FrancYescO** [comment] 2018-10-29 02:06
i think we have to reenable the install from the GUI and we can close this issue, as actually luci is working

**Closed** 2018-11-01 19:14 UTC
Labels: enhancement, help wanted, not a bug
