### ISSUE TITLE
Support for Telstra Smartmodem (DJA0230 Gen1)

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#627] opened 2019-04-14 07:17 UTC
Would love to see support for this modem.

Few challenges:
- Automatic fallover to mobile
- Extra leds

Problems:
- Mobile tab in web interface does not work at all. Can not enable disable mobile, datausage or different apn’s

**Comment by kevdagoat** [comment] 2019-04-14 07:42
Files:

- LTE stuff
[lte-profiles.lp.txt](https://github.com/Ansuel/tch-nginx-gui/files/3077116/lte-profiles.lp.txt)
[lte-sim.lp.txt](https://github.com/Ansuel/tch-nginx-gui/files/3077117/lte-sim.lp.txt)
[lte-sms.lp.txt](https://github.com/Ansuel/tch-nginx-gui/files/3077118/lte-sms.lp.txt)
[lte-doctor.lp.txt](https://github.com/Ansuel/tch-nginx-gui/files/3077119/lte-doctor.lp.txt)
[lte-modal.lp.txt](https://github.com/Ansuel/tch-nginx-gui/files/3077120/lte-modal.lp.txt)

- VoLTE Modal
[mmpbx-volte-modal.lp.txt](https://github.com/Ansuel/tch-nginx-gui/files/3077121/mmpbx-volte-modal.lp.txt)

- Transformer Mappings
[MobileD mappings.zip](https://github.com/Ansuel/tch-nginx-gui/files/3077123/MobileD.mappings.zip)
[Cellular Interface mappings.zip](https://github.com/Ansuel/tch-nginx-gui/files/3077124/Cellular.Interface.mappings.zip)

- stateMachines
[stateMachines.lua.txt](https://github.com/Ansuel/tch-nginx-gui/files/3077128/stateMachines.lua.txt)

**Comment by kevdagoat** [comment] 2019-04-14 07:43
Leds:
```
Reserved_19
dect:blue
dect:cyan
dect:green
dect:magenta
dect:orange
dect:red
dect:white
ethernet:blue
ethernet:cyan
ethernet:green
ethernet:magenta
ethernet:orange
ethernet:red
ethernet:white
internet:blue
internet:cyan
internet:green
internet:magenta
internet:orange
internet:red
internet:white
lte:blue
lte:cyan
lte:green
lte:magenta
lte:orange
lte:red
lte:white
power:blue
power:cyan
power:green
power:magenta
power:orange
power:red
power:white
voip:blue
voip:cyan
voip:green
voip:magenta
voip:orange
voip:red
voip:white
wireless:blue
wireless:cyan
wireless:green
wireless:magenta
wireless:orange
wireless:red
wireless:white
```

**Comment by FrancYescO** [comment] 2019-05-14 07:34
install log?
do you have and extracted rootfs?

**Comment by kevdagoat** [comment] 2019-05-15 08:42
[mtd3.zip](https://github.com/Ansuel/tch-nginx-gui/files/3181671/mtd3.zip)

```
root@mygateway:~# /etc/init.d/rootdevice debug
Root Script: Installing in progress...
Root Script: Disable watchdog
Root Script: Start rooting
Root Script: Setting root flag
Root Script: Reset unlock bit
Root Script: Save root password if modified
uci: Entry not found
Root Script: Setting & Enabling Dropbear SSH Server
uci: Entry not found
Root Script: Restarting Dropbear SSH Server
Root Script: Executing /etc/modgui_scripts/01_prereq.sh
Root Script: Executing /etc/modgui_scripts/02_specific.sh
Root Script: Applying specific model fixes...
Root Script: Removing fixes and resuming root process...
Root Script: Executing /etc/modgui_scripts/03_various.sh
Root Script: Fix Sysupgrade
Root Script: Restore original mapper
Root Script: Transformer lib check
Root Script: Old build detected, moving wansensing file
Root Script: Checking downgrade limitation bit
Root Script: Creating utility symbolic link
Root Script: Remove old update script
Root Script: Enabling hardware serial console...
Root Script: Add checkversion to cron...
Root Script: Executing /etc/modgui_scripts/04_config.sh
Root Script: Check original config
Root Script: Unlocking web interface if needed
Root Script: Check if variant_friendly_name set
Root Script: Remove https check
uci: Invalid argument
uci: Invalid argument
Root Script: Check for CSS themes
Root Script: Check driver setting
Root Script: Check Dropbear config file
Root Script: Check eco paramaters
Root Script: Restarting power management
Root Script: Create GUI type in config
Root Script: Add new web options
Root Script: New DHCPRelay Option
Root Script: Disable trace from igmpproxy
Root Script: Create new option for led definitions
Root Script: LedEventing new md5sum: e1fc0cbc7bde9a2f4b99f6d716abda7e
Root Script: LedEventing md5sum: dac6ce2752d6e4deaeb284f24525959e
Root Script: Creating and checking real version
Root Script: Implementing WoL
Cannot find device "lan"
Cannot find device "lan"
Warning: Option @zone[0].wan is unknown
Warning: Option @zone[1].wan is unknown
Warning: Section @zone[1] (Guest1) cannot resolve device of network 'Guest1'
Warning: Option @zone[2].wan is unknown
Warning: Section @zone[2] (Guest1_5GHz) cannot resolve device of network 'Guest1_5GHz'
Warning: Option @zone[3].wan is unknown
Warning: Section @zone[1] (Guest1) has no device, network, subnet or extra options
Warning: Section @zone[2] (Guest1_5GHz) has no device, network, subnet or extra options
 * Clearing IPv4 filter table
 * Clearing IPv4 nat table
 * Clearing IPv4 mangle table
 * Clearing IPv4 raw table
 * Populating IPv4 filter table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
   * Rule 'drop_lan_2_Guest1'
   * Rule 'drop_Guest1_2_lan'
   * Rule 'drop_lan_2_Guest1_5GHz'
   * Rule 'drop_Guest1_5GHz_2_lan'
   * Rule 'drop-lan_2_Guest1_GW'
   * Rule 'drop-lan_2_Guest1_5GHz_GW'
   * Rule 'drop-lan_2_hotspot'
   * Rule 'drop-Guest_2_hotspot'
   * Rule 'drop-Guest5G_2_hotspot'
   * Rule 'Allow-Guest1_ICMP'
   * Rule 'Allow-Guest1_DHCP'
   * Rule 'Allow-Guest1_DNS'
   * Rule 'Allow-Guest1_5GHz_ICMP'
   * Rule 'Allow-Guest1_5GHz_DHCP'
   * Rule 'Allow-Guest1_5GHz_DNS'
   * Rule 'Allow-DHCP-Renew'
   * Rule 'Deny-CUPS-lan'
   * Rule 'Deny-CUPS-wan'
   * Rule 'Default action for outgoing NAT'
   * Forward 'lan' -> 'wan'
   * Forward 'Guest1' -> 'wan'
   * Forward 'Guest1_5GHz' -> 'wan'
 * Populating IPv4 nat table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Populating IPv4 mangle table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Populating IPv4 raw table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Clearing IPv6 filter table
 * Clearing IPv6 mangle table
 * Clearing IPv6 raw table
 * Populating IPv6 filter table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
   * Rule 'drop_lan_2_Guest1'
   * Rule 'drop_Guest1_2_lan'
   * Rule 'drop_lan_2_Guest1_5GHz'
   * Rule 'drop_Guest1_5GHz_2_lan'
   * Rule 'Allow-Guest1_ICMPv6'
   * Rule 'Allow-Guest1_5GHz_ICMPv6'
   * Rule 'Allow-Ping6'
   * Rule 'Allow-DHCPv6'
   * Rule 'Allow-ICMPv6-Input'
   * Rule 'Allow-ICMPv6-Forward'
   * Rule 'Deny-CUPS-lan-v6'
   * Rule 'Deny-CUPS-wan-v6'
   * Rule 'Default action for outgoing NAT'
   * Forward 'lan' -> 'wan'
   * Forward 'Guest1' -> 'wan'
   * Forward 'Guest1_5GHz' -> 'wan'
 * Populating IPv6 mangle table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Populating IPv6 raw table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Set tcp_ecn to off
 * Set tcp_syncookies to on
   ! Unable to write value: No such file or directory
 * Set tcp_window_scaling to on
 * Running script '/lib/functions/firewall-ext-tch.sh'
 * Running script '/lib/functions/tod.sh'
iptables: Chain already exists.
ip6tables: Chain already exists.
 * Running script '/lib/functions/firewall-wol.sh'
   ! Skipping due to path error: No such file or directory
 * Running script '/usr/share/miniupnpd-tch/firewall.include'
 * Running script '/lib/functions/firewall-mmpbx.sh'
 * Running script '/lib/functions/weburl-tch.sh'
 * Running script '/lib/functions/firewall-dropbear.sh'
Root Script: Apply new xDSL options
Root Script: Adding fast cache options
Root Script: Checking if wan_mode option exists...
Root Script: Inizialize and start DoSprotect...
Root Script: Checking if intercept is enabled and disabling if it is...
Root Script: Disabling coredump reboot...
Root Script: Restoring nginx additional options if needed...
Root Script: Adding missing voicednd rule if needed
Root Script: Doing various checks and generating hashes...
Root Script: Setting update branch to STABLE
Root Script: Stable GUI not found in /root
Root Script: Moving stable GUI from /tmp to /root
Root Script: Updating GUI in /root folder from /tmp
Root Script: Assuming first time install, cleaning /www dir and re-extracting .bz2
Root Script: Detected upgrade!
Root Script: Old GUI hash:
Root Script: New GUI hash: de0aeb53b22802ec6de421711058c26b
Root Script: Resetting version info...
Root Script: Executing /etc/modgui_scripts/05_app.sh
Root Script: Trafficmon inizialization
killall: trafficmon: no process killed
Root Script: Move Aria2 dir
Root Script: Reinstalling Telstra GUI if needed...
Root Script: Executing /etc/modgui_scripts/06_network.sh
Root Script: Check and cleanup
Root Script: Remove default DNS Servers
Root Script: Purify WAN
Root Script: Fix DNS bug
Root Script: Check if dnsmasq daemon name is as we need it for the GUI
Root Script: Sync DHCP configuration for new GUI
Root Script: Attempt to clean the wansensing script from hardcoded interfaces...
Root Script: Cleaning WanSensing
Root Script: Cleaning cups firewall rule...
Warning: Option @zone[0].wan is unknown
Warning: Option @zone[1].wan is unknown
Warning: Section @zone[1] (Guest1) cannot resolve device of network 'Guest1'
Warning: Option @zone[2].wan is unknown
Warning: Section @zone[2] (Guest1_5GHz) cannot resolve device of network 'Guest1_5GHz'
Warning: Option @zone[3].wan is unknown
Warning: Section @zone[3] (wan) cannot resolve device of network 'wwan'
Warning: Section @zone[3] (wan) cannot resolve device of network 'wwan_4'
Warning: Section @zone[3] (wan) cannot resolve device of network 'wwan_6'
Warning: Section @zone[1] (Guest1) has no device, network, subnet or extra options
Warning: Section @zone[2] (Guest1_5GHz) has no device, network, subnet or extra options
 * Flushing IPv4 filter table
 * Flushing IPv4 nat table
 * Flushing IPv4 mangle table
 * Flushing IPv4 raw table
 * Flushing IPv6 filter table
 * Flushing IPv6 mangle table
 * Flushing IPv6 raw table
 * Flushing conntrack table ...
 * Populating IPv4 filter table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
   * Rule 'drop_lan_2_Guest1'
   * Rule 'drop_Guest1_2_lan'
   * Rule 'drop_lan_2_Guest1_5GHz'
   * Rule 'drop_Guest1_5GHz_2_lan'
   * Rule 'drop-lan_2_Guest1_GW'
   * Rule 'drop-lan_2_Guest1_5GHz_GW'
   * Rule 'drop-lan_2_hotspot'
   * Rule 'drop-Guest_2_hotspot'
   * Rule 'drop-Guest5G_2_hotspot'
   * Rule 'Allow-Guest1_ICMP'
   * Rule 'Allow-Guest1_DHCP'
   * Rule 'Allow-Guest1_DNS'
   * Rule 'Allow-Guest1_5GHz_ICMP'
   * Rule 'Allow-Guest1_5GHz_DHCP'
   * Rule 'Allow-Guest1_5GHz_DNS'
   * Rule 'Allow-DHCP-Renew'
   * Rule 'Deny-CUPS-wan'
   * Rule 'SSH_wan'
   * Rule 'Default action for outgoing NAT'
   * Forward 'lan' -> 'wan'
   * Forward 'Guest1' -> 'wan'
   * Forward 'Guest1_5GHz' -> 'wan'
 * Populating IPv4 nat table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Populating IPv4 mangle table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Populating IPv4 raw table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Populating IPv6 filter table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
   * Rule 'drop_lan_2_Guest1'
   * Rule 'drop_Guest1_2_lan'
   * Rule 'drop_lan_2_Guest1_5GHz'
   * Rule 'drop_Guest1_5GHz_2_lan'
   * Rule 'Allow-Guest1_ICMPv6'
   * Rule 'Allow-Guest1_5GHz_ICMPv6'
   * Rule 'Allow-Ping6'
   * Rule 'Allow-DHCPv6'
   * Rule 'Allow-ICMPv6-Input'
   * Rule 'Allow-ICMPv6-Forward'
   * Rule 'Deny-CUPS-lan-v6'
   * Rule 'Default action for outgoing NAT'
   * Forward 'lan' -> 'wan'
   * Forward 'Guest1' -> 'wan'
   * Forward 'Guest1_5GHz' -> 'wan'
 * Populating IPv6 mangle table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Populating IPv6 raw table
   * Zone 'lan'
   * Zone 'Guest1'
   * Zone 'Guest1_5GHz'
   * Zone 'wan'
 * Flushing conntrack: 101.172.130.47
 * Flushing conntrack: 2001:8004:18ea:7ac4:20:ff:fe00:0
 * Flushing conntrack: fe80::f020:ffff:fe2b:adcd
 * Flushing conntrack: 101.172.130.47
 * Flushing conntrack: 2001:8004:18ea:7ac4:20:ff:fe00:0
 * Flushing conntrack: fe80::f020:ffff:fe2b:adcd
 * Flushing conntrack: 101.172.130.47
 * Flushing conntrack: 2001:8004:18ea:7ac4:20:ff:fe00:0
 * Flushing conntrack: fe80::f020:ffff:fe2b:adcd
 * Set tcp_ecn to off
 * Set tcp_syncookies to on
   ! Unable to write value: No such file or directory
 * Set tcp_window_scaling to on
 * Running script '/etc/firewall.user'
 * Running script '/lib/functions/firewall-restart-ext-tch.sh'
 * Running script '/lib/functions/firewall-ext-tch.sh'
 * Running script '/lib/functions/tod.sh'
 * Running script '/usr/lib/intercept/firewall.sh'
 * Running script '/lib/functions/firewall-wol.sh'
   ! Skipping due to path error: No such file or directory
 * Running script '/usr/share/miniupnpd-tch/firewall.include'
 * Running script '/lib/functions/firewall-mmpbx.sh'
 * Running script '/lib/functions/weburl-tch.sh'
 * Running script '/lib/functions/firewall-dropbear.sh'
Root Script: Checking if ISP is detected...
uci: Invalid argument
Root Script: Executing /etc/modgui_scripts/99_postreq.sh
Root Script: Applying modifications
Root Script: Restarting dnsmasq if needed...
ash: 1: unknown operand
Root Script: Resetting cwmp and watchdog
Root Script: Process done.
Root Script: Restarting transformer
Root Script: Stopping nginx
Root Script: Restarting nginx...
```

**Comment by kevdagoat** [comment] 2019-05-15 08:47
![image](https://user-images.githubusercontent.com/42062334/57761855-f2f83880-7730-11e9-8ab3-4ac2e9d28160.png)

Mobile failover is working currently.

**Comment by kevdagoat** [comment] 2019-05-22 12:18
Now it isn't :(

**Comment by flywire** [comment] 2019-07-21 12:37
Extend to Support DJN2130 / VBNT-J, DJA0230 / VBNT-V, DJA0231 / VCNT-A Models: https://hack-technicolor.readthedocs.io/en/stable/Firmware%20Repository/

I  expect TG800vac / VANT-Y would form a good initial base.

> * Extra leds

See https://github.com/Ansuel/tch-nginx-gui/issues/264#issuecomment-428102932

@LuKePicci - is this repository compatible with https://hack-technicolor.readthedocs.io/en/latest/Hack%20Type%201&2/#post-root-procedures ?

**Comment by kevdagoat** [comment] 2019-07-21 12:43
@flywire

Eco button config should be the same

**Comment by flywire** [comment] 2019-07-21 13:38
Link was intended for the picture but doubt all Eco button issues fixed on TG800

**Comment by LuKePicci** [comment] 2019-07-21 14:15
@flywire I think this mod pack does bank planning on its own, if it differs you will end up with a different, not optimal one. Despite being not optima, this will not cause issues as far as this mod does not take the active == booted bank as guaranteed assumption.

**Comment by Ansuel** [comment] 2019-07-21 14:19
If you are talking about this gui

It will force bank 1
If for some reason you are on bank 1 but booted bank 2 and bank 2 is
rooted, then bank 1 gets erased and firmware and config on bank 2 are
copied...

Il Dom 21 Lug 2019, 16:15 Luca Piccirillo <notifications@github.com> ha
scritto:

**Comment by FrancYescO** [comment] 2019-08-21 12:18
Does actually the mobile card/tab work on this device or it just share the same problem as https://github.com/Ansuel/tch-nginx-gui/issues/768 ?

try restoring /etc/init.d/mobiled from /rom and restart service

for the mobile fallback to get it fixed we probably must have to look at the wansensing scripts (still  in /etc/wansensing on this device? the GUI is replacing L2Main.lua that if already exist in telstra fw can be the cause of breaking the mobile fallback)

Remote Assistance is working ?

**Comment by FrancYescO** [comment] 2020-12-16 10:24
closing this, report specific bugs if any

**Closed by FrancYescO** 2020-12-16 10:24 UTC
Labels: enhancement
