### ISSUE TITLE
Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/management/Packages.gz

### ISSUE THREAD

**Issue by Janaue** [Ansuel/tch-nginx-gui#837] opened 2019-09-26 05:02 UTC
hello

I have a DGA4132 GUI Version 9.4.94-da43de07 with firmware AGTHP_2.0.1_003. It does not find any package for the extra apps. Only Aria2 is installed and has a GUI.

this is for luci
`Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/packages/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/packages/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/routing/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/routing/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/telephony/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/telephony/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/management/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/management/Packages.gz Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages/Packages.gz *** Failed to download the package list from http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63Collected errors: * opkg_install_cNo packages removed. Unknown package 'libuci-lua'. Unknown package 'luci'. Unknown package 'rpcd'. stall_cmd: Cannot install package rpcd. mv: can't rename '/www/cgi-bin': No such file or directory mv: can't rename '/www/luci-static': No such file or directory mv: can't rename '/www/index.html': No such file or directory rm: can't remove '/usr/lib/lua/uci.so': No such file or directory sed: /usr/lib/lua/luci/model/uci.lua: No such file or directory uci: Entry not found uci: Entry not found uci: Entry not found uci: Entry not found uci: Entry not found uci: Entry not found uci: Entry not found uci: Entry not found uci: Entry not found uci: Entry not found uci: Entry not found /usr/share/transformer/scripts/appInstallRemoveUtility.sh: line 422: /etc/init.d/uhttpd: not found`

this is for Xupnp

`Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/packages/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/packages/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/routing/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/routing/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/telephony/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/telephony/Packages.gz Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/management/Packages.gz *** Failed to download the package list from https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/management/Packages.gz Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages/Packages.gz *** Failed to download the package list from http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63Collected errors: * opkg_install_cUnknown package 'xupnpd'. xupnpd.`

and so on for the remaining apps

**Comment by kevdagoat** [comment] 2019-09-26 11:07
Replace https with http in /etc/opkg/distfeeds.conf

**Comment by Janaue** [comment] 2019-09-30 12:04
In  /etc/opkg/distfeeds.conf
I have already
src/gz chaos_calmer http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages

**Comment by Janaue** [comment] 2019-09-30 12:04
this URL gives a 404

**Comment by FrancYescO** [comment] 2019-09-30 16:06
`http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages` is not intended to work, just an unused "placeholder" (no feed are configured by tch)

**Comment by Janaue** [comment] 2019-10-01 04:59
apps still fail on  [DEV] Version: 9.4.97

**Comment by Janaue** [comment] 2019-10-15 11:35
in putty i installed https://repository.ilpuntotecnico.com/files/Ansuel/AGTEF/modular/upgrade-pack-specificDGA.tar.bz2
and now the apps are installed. I still do not have telnet though

**Comment by FrancYescO** [comment] 2020-01-17 19:51
also telnet fixed in https://github.com/Ansuel/tch-nginx-gui/commit/90266c37ff70314806b5c2ea0566ccbe2b348180

**Closed by FrancYescO** 2020-01-17 19:51 UTC
Labels: bug, to confirm

**Comment by FrancYescO** [comment] 2021-07-01 09:41
Did you installed specific package from GUI modal? GUI was installed offline?

**Comment by islcom** [comment] 2021-07-01 11:16
using curl -k https://raw.githubusercontent.com/Ansuel/gui-dev-build-auto/master/GUI.tar.bz2 --output /tmp/GUI.tar.bz2
bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf -
/etc/init.d/rootdevice force
with internet connected wan

**Comment by islcom** [comment] 2021-07-01 11:23
used extensions card in GUI, internet connected

**Comment by FrancYescO** [comment] 2021-07-01 12:29
Post a debug zip. specific package looks installed from the modgui modal?

**Comment by islcom** [comment] 2021-07-01 23:05
Confirmed Luci working ok on TG789vac V2. 
Still have issues with DJA2130, there is no debug zip button in system extras?

**Comment by islcom** [comment] 2021-07-02 08:12
Debug file[](url)
[DebugHelper2021-07-02-1808.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/6753111/DebugHelper2021-07-02-1808.tar.gz)

Thanks

**Comment by FrancYescO** [comment] 2021-07-02 08:24
issue via SSH this command `uci set modgui.app.specific_app="0"` than go to modgui modal you should see a box that warn you to install specific app, try online installation and report log here

**Comment by islcom** [comment] 2021-07-02 10:30
Ran the command, tried to install Luci but fails with the same errors, have enclosed the log file.

Thanks[
[DebugHelper2021-07-02-2008.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/6753998/DebugHelper2021-07-02-2008.tar.gz)
](url)

**Comment by FrancYescO** [comment] 2021-07-02 12:47
i didn't say install luci, but install specific app from modgui modal.

until we don't find what's wrong here, luci will not install.

**Comment by islcom** [comment] 2021-07-02 22:05
Ran install specific app from modgui modal
result ; Complete
Package wget (1sh: bad number
sh: bad number
sh: bad number
Close
[DebugHelper2021-07-03-0759.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/6757241/DebugHelper2021-07-03-0759.tar.gz)
